# Generated by Django 2.2.12 on 2021-05-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_id', models.CharField(max_length=10)),
                ('customer_name', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('SE', 'Self Employed'), ('SL', 'Salaried')], max_length=100)),
                ('loan_amount', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=5, max_digits=10)),
                ('status', models.CharField(default='Pending', max_length=100)),
            ],
        ),
    ]
