# Generated by Django 2.2.12 on 2021-05-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userenquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userenquiry',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
